// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2M_McrHAP3ZHC_HxsywPFcTndTq1GTEA',
    appId: '1:645126577121:web:f83d33d7b6647ace86d0a0',
    messagingSenderId: '645126577121',
    projectId: 'crud-9b277',
    authDomain: 'crud-9b277.firebaseapp.com',
    storageBucket: 'crud-9b277.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj5Eb5tPewbzv67d2tdMZjr4SkxfMTEJ4',
    appId: '1:645126577121:android:e1a392000e3eadd886d0a0',
    messagingSenderId: '645126577121',
    projectId: 'crud-9b277',
    storageBucket: 'crud-9b277.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW_5Is0usJBdhhtBbuAJN1V2rrm0RhPu0',
    appId: '1:645126577121:ios:9a47f939e092e0f686d0a0',
    messagingSenderId: '645126577121',
    projectId: 'crud-9b277',
    storageBucket: 'crud-9b277.appspot.com',
    iosBundleId: 'com.example.solving',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW_5Is0usJBdhhtBbuAJN1V2rrm0RhPu0',
    appId: '1:645126577121:ios:3c05b35d0acfeac786d0a0',
    messagingSenderId: '645126577121',
    projectId: 'crud-9b277',
    storageBucket: 'crud-9b277.appspot.com',
    iosBundleId: 'com.example.solving.RunnerTests',
  );
}
